"use client";

import React from "react";
import type { PmrDocument, PmrSectionId } from "@odyssey/types";
import { PmrPage } from "./PmrPage";
import { PmrSection } from "./PmrSection";
import { PmrTable } from "./PmrTable";
import { AlertBanner } from "./AlertBanner";
import { SignatureBlock } from "./SignatureBlock";
import { QrVerify } from "./QrVerify";

export interface PmrDocumentViewProps {
  document: PmrDocument;
  className?: string;
}

export function PmrDocumentView({ document, className = "" }: PmrDocumentViewProps) {
  const {
    facilityHeader: h,
    controlBlock: c,
    patientIdentification: p,
    alertsBanner: a,
    problemList: pr,
    currentMedications: m,
    vitalSignsTrend: v,
    encounterHistory: e,
    diagnosticResults: d,
    proceduresAndImmunizations: pi,
    pastMedicalHistory: pmh,
    attachmentsIndex: att,
    attestationAndSignatures: sig,
    footer: f,
    options,
  } = document;

  const included = new Set<PmrSectionId>(options.sectionsIncluded);

  return (
    <PmrPage pageSize={options.pageSize} className={className}>
      {/* Watermark Overlay (if draft, uncontrolled, or voided) */}
      {c.watermark && (
        <div className="pmr-watermark-overlay" aria-hidden="true">
          {c.watermark}
        </div>
      )}

      {/* 1. Header (repeats on every page) */}
      {included.has("header") && (
        <header className="pmr-header">
          <div>
            <h1 className="pmr-facility-name">{h.facilityName}</h1>
            <div className="pmr-facility-sub">
              <div>{h.facilityAddress} · Tel: {h.contactNumber}</div>
              {h.email && <div>Email: {h.email}</div>}
              <div>
                DOH License: <strong>{h.dohLicenseNumber || "Active"}</strong> · PhilHealth Acc.:{" "}
                <strong>{h.philhealthAccreditationNumber || "Active"}</strong>
              </div>
            </div>
          </div>
          <div className="pmr-doc-title-block">
            <div className="pmr-doc-title">{h.documentTitle}</div>
            {h.subtitle && (
              <div style={{ fontSize: "0.75rem", color: "#173f3b", fontWeight: 600, marginTop: 2 }}>
                {h.subtitle}
              </div>
            )}
            <span className="pmr-copy-badge">{c.copyType}</span>
          </div>
        </header>
      )}

      {/* 2. Document Control Block */}
      {included.has("control_block") && (
        <div className="pmr-control-block" aria-label="Document Control Block">
          <div className="pmr-control-item">
            <strong>Document ID</strong>
            <span style={{ fontFamily: "monospace" }}>{c.documentId}</span>
          </div>
          <div className="pmr-control-item">
            <strong>Patient MRN</strong>
            <span style={{ fontFamily: "monospace" }}>{c.mrn}</span>
          </div>
          <div className="pmr-control-item">
            <strong>Date / Time Generated</strong>
            <span>{c.generatedAtReadable}</span>
          </div>
          <div className="pmr-control-item">
            <strong>Purpose of Release</strong>
            <span>{c.purposeOfRelease}</span>
          </div>
          <div className="pmr-control-item">
            <strong>Generated By</strong>
            <span>{c.generatedBy.name} ({c.generatedBy.role})</span>
          </div>
          <div className="pmr-control-item">
            <strong>Record Revision</strong>
            <span>Rev. {c.recordRevision}</span>
          </div>
          <div className="pmr-control-item" style={{ gridColumn: "span 2" }}>
            <strong>SHA-256 Non-Repudiation Digest</strong>
            <code style={{ fontSize: "7pt", wordBreak: "break-all" }}>{c.sha256Hash}</code>
          </div>
        </div>
      )}

      {/* 3. Patient Identification */}
      {included.has("patient_identification") && (
        <PmrSection title="Patient Identification">
          <table className="pmr-table">
            <tbody>
              <tr>
                <th style={{ width: "20%" }}>Full Name</th>
                <td style={{ width: "30%", fontWeight: "bold" }}>{p.fullName}</td>
                <th style={{ width: "20%" }}>Sex / Gender</th>
                <td style={{ width: "30%" }}>{p.sex}</td>
              </tr>
              <tr>
                <th>Date of Birth &amp; Age</th>
                <td>{p.dateOfBirth} ({p.ageFormatted})</td>
                <th>Civil Status</th>
                <td>{p.civilStatus}</td>
              </tr>
              <tr>
                <th>Residential Address</th>
                <td>{p.residentialAddress}</td>
                <th>Contact Details</th>
                <td>{p.contactNumber} {p.emailAddress ? `· ${p.emailAddress}` : ""}</td>
              </tr>
              <tr>
                <th>PhilHealth No.</th>
                <td><strong>{p.philhealthNumber}</strong></td>
                <th>HMO / Healthcare Plan</th>
                <td>{p.hmoDetails.providerName} ({p.hmoDetails.policyNumber})</td>
              </tr>
              <tr>
                <th>Blood Type</th>
                <td><strong>{p.bloodType}</strong></td>
                <th>Emergency Contact</th>
                <td>{p.emergencyContact.name} ({p.emergencyContact.relationship}) - {p.emergencyContact.contactNumber}</td>
              </tr>
            </tbody>
          </table>
        </PmrSection>
      )}

      {/* 4. Alerts Banner (Allergies & Critical Warnings) */}
      {included.has("alerts_banner") && <AlertBanner alerts={a} />}

      {/* 5. Problem List / Diagnoses */}
      {included.has("problem_list") && (
        <PmrSection title="Problem List / Diagnoses">
          <PmrTable
            data={pr.activeProblems}
            emptyMessage={pr.statement}
            columns={[
              {
                header: "ICD-10",
                accessor: (row) => <code>{row.code}</code>,
                width: "15%",
              },
              {
                header: "Diagnosis Description",
                accessor: (row) => <strong>{row.display}</strong>,
                width: "55%",
              },
              {
                header: "Clinical Status",
                accessor: (row) => (
                  <span style={{ textTransform: "capitalize" }}>{row.clinicalStatus}</span>
                ),
                width: "15%",
              },
              {
                header: "Onset Date",
                accessor: (row) => row.onsetDate || "Recorded",
                width: "15%",
              },
            ]}
          />
          {pr.resolvedProblems.length > 0 && (
            <div style={{ marginTop: 8 }}>
              <strong style={{ fontSize: "8pt", textTransform: "uppercase", color: "#555" }}>
                Resolved Conditions
              </strong>
              <PmrTable
                data={pr.resolvedProblems}
                columns={[
                  { header: "Code", accessor: (row) => <code>{row.code}</code>, width: "15%" },
                  { header: "Resolved Diagnosis", accessor: (row) => row.display, width: "55%" },
                  { header: "Resolved Date", accessor: (row) => row.resolvedDate || "Resolved", width: "30%" },
                ]}
              />
            </div>
          )}
        </PmrSection>
      )}

      {/* 6. Current Medications */}
      {included.has("current_medications") && (
        <PmrSection title="Current Medications">
          <PmrTable
            data={m.medications}
            emptyMessage={m.statement}
            columns={[
              {
                header: "Drug Name & Strength",
                accessor: (row) => <strong>{row.drugName}</strong>,
                width: "28%",
              },
              {
                header: "Dosage & Instructions",
                accessor: (row) => row.dosage,
                width: "28%",
              },
              {
                header: "Route",
                accessor: (row) => row.route,
                width: "12%",
              },
              {
                header: "Frequency",
                accessor: (row) => row.frequency,
                width: "14%",
              },
              {
                header: "Prescriber",
                accessor: (row) => row.prescriberName,
                width: "18%",
              },
            ]}
          />
        </PmrSection>
      )}

      {/* 7. Vital Signs Trend */}
      {included.has("vital_signs_trend") && (
        <PmrSection title="Vital Signs Trend">
          <PmrTable
            data={v.historicalReadings}
            emptyMessage={v.statement}
            columns={[
              { header: "Date / Time (PHT)", accessor: (row) => row.recordedAtFormatted, width: "24%" },
              { header: "Blood Pressure", accessor: (row) => <strong>{row.bloodPressure}</strong>, width: "16%" },
              { header: "HR (bpm)", accessor: (row) => row.heartRateBpm, width: "12%" },
              { header: "RR (/min)", accessor: (row) => row.respiratoryRateBpm, width: "12%" },
              { header: "Temp (°C)", accessor: (row) => `${row.temperatureCelsius}°C`, width: "12%" },
              { header: "SpO2", accessor: (row) => `${row.oxygenSaturationPct}%`, width: "12%" },
              { header: "BMI", accessor: (row) => row.bmi ?? "N/A", width: "12%" },
            ]}
          />
        </PmrSection>
      )}

      {/* 8. Encounter History (Reverse Chronological) */}
      {included.has("encounter_history") && (
        <PmrSection title="Encounter History">
          {e.encounters.length === 0 ? (
            <p style={{ fontStyle: "italic", fontSize: "8.5pt", color: "#555" }}>
              {e.statement}
            </p>
          ) : (
            e.encounters.map((enc) => (
              <article key={enc.id} className="pmr-encounter-card">
                <div className="pmr-encounter-head">
                  <div>
                    <strong>{enc.dateFormatted}</strong> ·{" "}
                    <span style={{ fontWeight: 600 }}>{enc.serviceName}</span> ({enc.type})
                  </div>
                  <div>
                    Attending: <strong>{enc.attendingPhysician}</strong> {enc.prcLicenseNo ? `(${enc.prcLicenseNo})` : "(MD)"}
                  </div>
                </div>
                <div style={{ margin: "4px 0", fontSize: "8.5pt" }}>
                  <strong>Chief Complaint:</strong> {enc.chiefComplaint}
                </div>
                {enc.soapSummary && (
                  <div
                    style={{
                      fontSize: "8pt",
                      color: "#374151",
                      margin: "4px 0",
                      background: "#f9fafb",
                      padding: "6px 8px",
                      borderRadius: "4px",
                      borderLeft: "3px solid #173f3b",
                    }}
                  >
                    {enc.soapSummary.rawNote && !enc.soapSummary.subjective ? (
                      <div>
                        <strong>Consultation Note:</strong> {enc.soapSummary.rawNote}
                      </div>
                    ) : (
                      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "4px 12px" }}>
                        <div>
                          <strong style={{ color: "#173f3b" }}>S (Subjective):</strong> {enc.soapSummary.subjective}
                        </div>
                        <div>
                          <strong style={{ color: "#173f3b" }}>O (Objective):</strong> {enc.soapSummary.objective}
                        </div>
                        <div>
                          <strong style={{ color: "#173f3b" }}>A (Assessment):</strong> {enc.soapSummary.assessment}
                        </div>
                        <div>
                          <strong style={{ color: "#173f3b" }}>P (Plan):</strong> {enc.soapSummary.plan}
                        </div>
                      </div>
                    )}
                  </div>
                )}
                {enc.diagnoses.length > 0 && (
                  <div style={{ fontSize: "8pt", marginTop: 2 }}>
                    <strong>Encounter Diagnoses:</strong> {enc.diagnoses.join(", ")}
                  </div>
                )}
                {enc.ordersSummary.length > 0 && (
                  <div style={{ fontSize: "8pt", marginTop: 2 }}>
                    <strong>Orders &amp; Prescriptions:</strong> {enc.ordersSummary.join("; ")}
                  </div>
                )}
                <div style={{ fontSize: "8pt", color: "#173f3b", marginTop: 2 }}>
                  <strong>Disposition:</strong> {enc.disposition}
                </div>
              </article>
            ))
          )}
        </PmrSection>
      )}

      {/* 9. Laboratory and Diagnostic Results */}
      {included.has("diagnostic_results") && (
        <PmrSection title="Laboratory &amp; Diagnostic Results">
          <PmrTable
            data={d.results}
            emptyMessage={d.statement}
            columns={[
              { header: "Test Name", accessor: (row) => <strong>{row.testName}</strong>, width: "30%" },
              { header: "Value", accessor: (row) => <span>{row.value}</span>, width: "15%" },
              { header: "Unit", accessor: (row) => row.unit || "—", width: "10%" },
              { header: "Reference Range", accessor: (row) => row.referenceRange, width: "20%" },
              {
                header: "Flag",
                accessor: (row) => (
                  <span
                    className={
                      row.abnormalFlag === "CRITICAL"
                        ? "flag-critical"
                        : row.abnormalFlag !== "NORMAL"
                        ? "flag-high"
                        : ""
                    }
                  >
                    {row.abnormalFlag}
                  </span>
                ),
                width: "10%",
              },
              { header: "Result Date", accessor: (row) => row.resultDate, width: "15%" },
            ]}
          />
        </PmrSection>
      )}

      {/* 10. Procedures, Immunizations, Referrals, and Issued Medical Certificates */}
      {included.has("procedures_and_immunizations") && (
        <PmrSection title="Procedures, Immunizations, Referrals &amp; Certificates">
          {pi.procedures.length > 0 && (
            <div style={{ marginBottom: 8 }}>
              <strong style={{ fontSize: "8.5pt", textTransform: "uppercase" }}>Procedures</strong>
              <PmrTable
                data={pi.procedures}
                columns={[
                  { header: "Procedure", accessor: (row) => <strong>{row.name}</strong>, width: "40%" },
                  { header: "Date Performed", accessor: (row) => row.performedDate, width: "25%" },
                  { header: "Performed By", accessor: (row) => row.performedByName, width: "35%" },
                ]}
              />
            </div>
          )}

          {pi.immunizations.length > 0 && (
            <div style={{ marginBottom: 8 }}>
              <strong style={{ fontSize: "8.5pt", textTransform: "uppercase" }}>Immunizations</strong>
              <PmrTable
                data={pi.immunizations}
                columns={[
                  { header: "Vaccine", accessor: (row) => <strong>{row.vaccineName}</strong>, width: "35%" },
                  { header: "Dose", accessor: (row) => `Dose ${row.doseNumber}`, width: "15%" },
                  { header: "Administered Date", accessor: (row) => row.administeredDate, width: "25%" },
                  { header: "Lot No.", accessor: (row) => row.lotNumber || "Recorded", width: "25%" },
                ]}
              />
            </div>
          )}

          {pi.referrals.length > 0 && (
            <div style={{ marginBottom: 8 }}>
              <strong style={{ fontSize: "8.5pt", textTransform: "uppercase" }}>Specialist Referrals</strong>
              <PmrTable
                data={pi.referrals}
                columns={[
                  { header: "Referred Facility / Specialist", accessor: (row) => <strong>{row.referredTo}</strong>, width: "35%" },
                  { header: "Specialty", accessor: (row) => row.specialty, width: "20%" },
                  { header: "Reason", accessor: (row) => row.reason, width: "30%" },
                  { header: "Priority", accessor: (row) => row.priority, width: "15%" },
                ]}
              />
            </div>
          )}

          {pi.medicalCertificates.length > 0 && (
            <div>
              <strong style={{ fontSize: "8.5pt", textTransform: "uppercase" }}>Issued Medical Certificates</strong>
              <PmrTable
                data={pi.medicalCertificates}
                columns={[
                  { header: "Certificate Title", accessor: (row) => <strong>{row.documentTitle}</strong>, width: "35%" },
                  { header: "Clinical Clearance Statement", accessor: (row) => row.statement, width: "45%" },
                  { header: "Date Issued", accessor: (row) => row.issuedDate, width: "20%" },
                ]}
              />
            </div>
          )}

          {pi.procedures.length === 0 &&
            pi.immunizations.length === 0 &&
            pi.referrals.length === 0 &&
            pi.medicalCertificates.length === 0 && (
              <p style={{ fontStyle: "italic", fontSize: "8.5pt", color: "#555" }}>
                No procedures, immunizations, referrals, or certificates on record.
              </p>
            )}
        </PmrSection>
      )}

      {/* 11. Past Medical, Surgical, Family, and Social History */}
      {included.has("past_medical_history") && (
        <PmrSection title="Past Medical, Surgical, Family &amp; Social History">
          <table className="pmr-table">
            <tbody>
              <tr>
                <th style={{ width: "25%" }}>Past Medical Conditions</th>
                <td style={{ width: "75%" }}>{pmh.pastMedicalConditions.join("; ") || "Unremarkable"}</td>
              </tr>
              <tr>
                <th>Past Surgical History</th>
                <td>{pmh.pastSurgicalHistory.join("; ") || "No past surgical operations recorded"}</td>
              </tr>
              <tr>
                <th>Family Medical History</th>
                <td>{pmh.familyHistory.join("; ") || "Non-contributory"}</td>
              </tr>
              <tr>
                <th>Social &amp; Lifestyle History</th>
                <td>
                  Tobacco: <strong>{pmh.socialHistory.tobaccoUse}</strong> · Alcohol:{" "}
                  <strong>{pmh.socialHistory.alcoholUse}</strong> · Occupation: {pmh.socialHistory.occupationalExposure}
                </td>
              </tr>
            </tbody>
          </table>
        </PmrSection>
      )}

      {/* 12. Attachments Index (No heavy embedding) */}
      {included.has("attachments_index") && (
        <PmrSection title="Attachments Index">
          <PmrTable
            data={att.attachments}
            emptyMessage={att.statement}
            columns={[
              { header: "Attachment Title", accessor: (row) => <strong>{row.title}</strong>, width: "40%" },
              { header: "Document Type", accessor: (row) => row.documentType, width: "25%" },
              { header: "Format", accessor: (row) => row.fileFormat, width: "15%" },
              { header: "Date Cataloged", accessor: (row) => row.dateCreated, width: "20%" },
            ]}
          />
        </PmrSection>
      )}

      {/* 13. Attestation and Signature Block */}
      {included.has("attestation_and_signatures") && (
        <SignatureBlock attestation={sig} generatedAtReadable={c.generatedAtReadable} />
      )}

      {/* 14. Footer (repeats on every page) */}
      {included.has("footer") && (
        <footer className="pmr-footer">
          <div>
            <div style={{ fontWeight: "bold" }}>
              Doc ID: {f.documentId} · Rev: {f.revision} · Confidential Healthcare Record
            </div>
            <div style={{ marginTop: 2 }}>{f.dataPrivacyNotice}</div>
          </div>
          <QrVerify payload={f.qrVerificationPayload} documentId={f.documentId} size={64} />
        </footer>
      )}
    </PmrPage>
  );
}
