"use client";

import {
  createBrowserSupabaseClient,
  getAccessibleOrganizations,
  getCurrentUserEmail,
  getLaboratoryServices,
  getPortalAccess,
  hasOrganizationPermission,
  saveLaboratoryService,
  signInWithPassword,
  signOut,
} from "@odyssey/supabase-client";
import type { LaboratoryServiceSummary, PublicClinicSummary } from "@odyssey/types";
import { Button, DataTable, Field, Input } from "@odyssey/ui";
import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";

export default function LaboratoryServicesPage() {
  const [email, setEmail] = useState("admin@synthetic.odyssey.test");
  const [password, setPassword] = useState("");
  const [signedInAs, setSignedInAs] = useState<string | null>(null);
  const [clinics, setClinics] = useState<PublicClinicSummary[]>([]);
  const [organizationId, setOrganizationId] = useState("");
  const [services, setServices] = useState<LaboratoryServiceSummary[]>([]);
  const [editing, setEditing] = useState<LaboratoryServiceSummary | null>(null);
  const [allowed, setAllowed] = useState(false);
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState("Sign in as an admin or owner to manage laboratory services.");

  const load = async (clinicId: string) => {
    const client = createBrowserSupabaseClient();
    const [permission, result] = await Promise.all([
      hasOrganizationPermission(client, clinicId, "can_manage_laboratory_services"),
      getLaboratoryServices(client, clinicId),
    ]);
    setAllowed(!permission.error && permission.data);
    if (result.error) setStatus(`Unable to load laboratory services: ${result.error.message}`);
    else setServices(result.data);
  };

  const initialize = async () => {
    const client = createBrowserSupabaseClient();
    const access = await getPortalAccess(client, "admin");
    if (access.error || !access.data.allowed) return;
    const organizations = await getAccessibleOrganizations(client, access.data.organizationIds);
    if (organizations.error || !organizations.data.length) return;
    const clinicId = organizations.data[0].id;
    setClinics(organizations.data); setOrganizationId(clinicId);
    const currentEmail = await getCurrentUserEmail(client);
    setSignedInAs(currentEmail.data ?? "Signed-in user");
    await load(clinicId);
  };

  useEffect(() => { void initialize(); }, []);

  async function handleSignIn(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true);
    const result = await signInWithPassword(createBrowserSupabaseClient(), email, password);
    setBusy(false);
    if (result.error) return setStatus(`Unable to sign in: ${result.error.message}`);
    await initialize();
  }

  async function handleSave(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!organizationId) return;
    const form = new FormData(event.currentTarget); setBusy(true);
    const result = await saveLaboratoryService(createBrowserSupabaseClient(), {
      id: editing?.id, organizationId, name: String(form.get("name") ?? ""),
      labCost: Number(form.get("labCost")), active: form.get("active") === "on",
    });
    setBusy(false);
    if (result.error) return setStatus(`Unable to save laboratory service: ${result.error.message}`);
    setEditing(null); event.currentTarget.reset(); setStatus("Laboratory service saved. Its code was generated by the system.");
    await load(organizationId);
  }

  if (!signedInAs) return <main><p className="eyebrow">Laboratory service catalog</p><h1>Admin and owner access</h1><form onSubmit={handleSignIn} className="stack narrow-form"><Field label="Email"><Input value={email} onChange={(e) => setEmail(e.target.value)} type="email" required /></Field><Field label="Password"><Input value={password} onChange={(e) => setPassword(e.target.value)} type="password" required /></Field><Button type="submit" disabled={busy}>Sign in</Button><p className="hint">{status}</p></form></main>;

  return <main><p className="eyebrow">Laboratory service catalog</p><h1>Laboratory services</h1><div className="session"><span>Signed in as {signedInAs}</span><span className="session-actions"><Link href="/">Back to appointments</Link><Button variant="secondary" onClick={() => void signOut(createBrowserSupabaseClient()).then(() => location.reload())}>Sign out</Button></span></div>
    {clinics.length > 1 && <Field label="Clinic workspace"><select className="odyssey-input" value={organizationId} onChange={(e) => { setOrganizationId(e.target.value); void load(e.target.value); }}>{clinics.map((clinic) => <option key={clinic.id} value={clinic.id}>{clinic.name}</option>)}</select></Field>}
    {!allowed ? <p className="hint">Only the clinic admin or owner can manage laboratory services.</p> : <><section><h2>{editing ? "Edit laboratory service" : "Add laboratory service"}</h2><form className="stack narrow-form" onSubmit={handleSave}><Field label="Laboratory service"><Input name="name" defaultValue={editing?.name ?? ""} key={editing?.id ?? "new"} required /></Field><Field label="Lab cost (PHP)"><Input name="labCost" type="number" min="0" step="0.01" defaultValue={editing?.labCost ?? ""} key={`cost-${editing?.id ?? "new"}`} required /></Field><label><input name="active" type="checkbox" defaultChecked={editing?.active ?? true} key={`active-${editing?.id ?? "new"}`} /> Active</label><span className="table-actions"><Button type="submit" disabled={busy}>{editing ? "Save changes" : "Add service"}</Button>{editing && <Button type="button" variant="outline" onClick={() => setEditing(null)}>Cancel</Button>}</span></form></section><DataTable caption="Laboratory services and their system-generated codes." data={services} emptyMessage="No laboratory services configured." getRowId={(service) => service.id} columns={[{ id: "code", header: "Code", cell: (service) => service.code }, { id: "name", header: "Laboratory service", cell: (service) => service.name }, { id: "cost", header: "Lab cost", cell: (service) => `PHP ${service.labCost.toFixed(2)}` }, { id: "status", header: "Status", cell: (service) => service.active ? "Active" : "Inactive" }, { id: "action", header: "", cell: (service) => <Button size="sm" variant="outline" onClick={() => setEditing(service)}>Edit</Button> }]} /></>}
    <p className="hint">{status}</p></main>;
}
