"use client";

import {
  deleteLaboratoryService,
  getLaboratoryServices,
  saveLaboratoryService,
} from "@odyssey/supabase-client";
import type { LaboratoryServiceSummary } from "@odyssey/types";
import { Button, DataTable, Field, Input } from "@odyssey/ui";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { AdminSignIn } from "../../components/admin-sign-in";
import { useAdminData } from "../../components/admin-data-context";
import { Dialog } from "../../components/ui/dialog";

export default function LaboratoryServicesPage() {
  const {
    client,
    email,
    error: accessError,
    organization,
    permissions,
  } = useAdminData();
  const [services, setServices] = useState<LaboratoryServiceSummary[]>([]);
  const [editing, setEditing] = useState<LaboratoryServiceSummary | null>(null);
  const [deletingService, setDeletingService] =
    useState<LaboratoryServiceSummary | null>(null);
  const [saving, setSaving] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [deleteError, setDeleteError] = useState<string | null>(null);
  const [status, setStatus] = useState("Loading laboratory services...");
  const allowed = permissions.includes("can_manage_laboratory_services");
  const busy = saving || deleting;

  const load = useCallback(
    async (clinicId: string) => {
      const result = await getLaboratoryServices(client, clinicId);
      if (result.error) {
        setStatus(
          `Unable to load laboratory services: ${result.error.message}`,
        );
        return false;
      }
      setServices(result.data);
      setStatus("Laboratory service catalog is up to date.");
      return true;
    },
    [client],
  );

  useEffect(() => {
    if (!organization || !allowed) return;
    void load(organization.id);
  }, [allowed, load, organization]);

  async function handleSave(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!organization) return;

    // React releases the synthetic event after an await. Keep the form element now so reset()
    // always targets the submitted form rather than event.currentTarget (which can become null).
    const formElement = event.currentTarget;
    const form = new FormData(formElement);
    const labCost = Number(form.get("labCost"));

    if (!Number.isFinite(labCost) || labCost < 0) {
      setStatus("Enter a valid lab cost of PHP 0.00 or more.");
      return;
    }

    setSaving(true);
    try {
      const result = await saveLaboratoryService(client, {
        id: editing?.id,
        organizationId: organization.id,
        name: String(form.get("name") ?? ""),
        labCost,
        active: form.get("active") === "on",
      });
      if (result.error) {
        setStatus(`Unable to save laboratory service: ${result.error.message}`);
        return;
      }

      formElement.reset();
      setEditing(null);
      const refreshed = await load(organization.id);
      if (refreshed)
        setStatus(
          "Laboratory service saved. Its code is generated by the system.",
        );
    } catch (error) {
      setStatus(
        `Unable to save laboratory service: ${error instanceof Error ? error.message : "Unexpected error"}`,
      );
    } finally {
      setSaving(false);
    }
  }

  async function handleDelete() {
    if (!organization || !deletingService) return;

    const service = deletingService;
    setDeleting(true);
    setDeleteError(null);
    try {
      const result = await deleteLaboratoryService(client, {
        id: service.id,
        organizationId: organization.id,
      });
      if (result.error) {
        setDeleteError(result.error.message);
        return;
      }

      if (editing?.id === service.id) setEditing(null);
      setDeletingService(null);
      const refreshed = await load(organization.id);
      if (refreshed)
        setStatus(`Laboratory service \"${service.name}\" was deleted.`);
    } catch (error) {
      setDeleteError(
        error instanceof Error ? error.message : "Unexpected error",
      );
    } finally {
      setDeleting(false);
    }
  }

  if (!email && accessError) return <AdminSignIn />;

  return (
    <main>
      <p className="eyebrow">Laboratory service catalog</p>
      <h1>Laboratory services</h1>
      <section>
        <h2>
          {editing ? "Edit laboratory service" : "Add laboratory service"}
        </h2>
        <form className="stack narrow-form" onSubmit={handleSave}>
          <Field label="Laboratory service">
            <Input
              name="name"
              defaultValue={editing?.name ?? ""}
              key={editing?.id ?? "new"}
              required
            />
          </Field>
          <Field label="Lab cost (PHP)">
            <Input
              name="labCost"
              type="number"
              min="0"
              step="0.01"
              defaultValue={editing?.labCost ?? ""}
              key={`cost-${editing?.id ?? "new"}`}
              required
            />
          </Field>
          <label>
            <input
              name="active"
              type="checkbox"
              defaultChecked={editing?.active ?? true}
              key={`active-${editing?.id ?? "new"}`}
            />{" "}
            Active
          </label>
          <span className="table-actions">
            <Button type="submit" disabled={busy}>
              {saving ? "Saving..." : editing ? "Save changes" : "Add service"}
            </Button>
            {editing && (
              <Button
                type="button"
                variant="outline"
                disabled={busy}
                onClick={() => setEditing(null)}
              >
                Cancel
              </Button>
            )}
          </span>
        </form>
      </section>
      <DataTable
        caption="Laboratory services and their system-generated codes."
        data={services}
        emptyMessage="No laboratory services configured."
        getRowId={(service) => service.id}
        columns={[
          { id: "code", header: "Code", cell: (service) => service.code },
          {
            id: "name",
            header: "Laboratory service",
            cell: (service) => service.name,
          },
          {
            id: "cost",
            header: "Lab cost",
            cell: (service) => `PHP ${service.labCost.toFixed(2)}`,
          },
          {
            id: "status",
            header: "Status",
            cell: (service) => (service.active ? "Active" : "Inactive"),
          },
          {
            id: "action",
            header: "Actions",
            cell: (service) => (
              <span className="table-actions">
                <Button
                  size="sm"
                  variant="outline"
                  disabled={busy}
                  onClick={() => setEditing(service)}
                >
                  Edit
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  disabled={busy}
                  onClick={() => {
                    setDeleteError(null);
                    setDeletingService(service);
                  }}
                >
                  Delete
                </Button>
              </span>
            ),
          },
        ]}
      />
      <p className="hint" role="status">
        {status}
      </p>
      <Dialog
        open={deletingService !== null}
        onOpenChange={(open) => {
          if (!open && !deleting) {
            setDeletingService(null);
            setDeleteError(null);
          }
        }}
        title="Delete laboratory service"
        description="This permanently removes the catalog item and records the change in the administrative audit log."
      >
        <div className="dialog-body">
          <div className="confirmation-summary">
            <span>Laboratory service</span>
            <strong>{deletingService?.name}</strong>
          </div>
          {deleteError ? (
            <p className="form-error" role="alert">
              Unable to delete laboratory service: {deleteError}
            </p>
          ) : null}
          <div className="dialog-actions">
            <Button
              variant="outline"
              disabled={deleting}
              onClick={() => setDeletingService(null)}
            >
              Cancel
            </Button>
            <Button disabled={deleting} onClick={() => void handleDelete()}>
              {deleting ? "Deleting..." : "Delete service"}
            </Button>
          </div>
        </div>
      </Dialog>
    </main>
  );
}
