"use client";

import { getLaboratoryServices, saveLaboratoryService } from "@odyssey/supabase-client";
import type { LaboratoryServiceSummary } from "@odyssey/types";
import { Button, DataTable, Field, Input } from "@odyssey/ui";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { AdminSignIn } from "../../components/admin-sign-in";
import { useAdminData } from "../../components/admin-data-context";

export default function LaboratoryServicesPage() {
  const { client, email, error: accessError, organization, permissions } = useAdminData();
  const [services, setServices] = useState<LaboratoryServiceSummary[]>([]);
  const [editing, setEditing] = useState<LaboratoryServiceSummary | null>(null);
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState("Loading laboratory services…");
  const allowed = permissions.includes("can_manage_laboratory_services");

  const load = useCallback(async (clinicId: string) => {
    const result = await getLaboratoryServices(client, clinicId);
    if (result.error) setStatus(`Unable to load laboratory services: ${result.error.message}`);
    else {
      setServices(result.data);
      setStatus("Laboratory service catalog is up to date.");
    }
  }, [client]);

  useEffect(() => {
    if (!organization || !allowed) return;
    void load(organization.id);
  }, [allowed, load, organization]);

  async function handleSave(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!organization) return;
    const form = new FormData(event.currentTarget);
    setBusy(true);
    const result = await saveLaboratoryService(client, {
      id: editing?.id,
      organizationId: organization.id,
      name: String(form.get("name") ?? ""),
      labCost: Number(form.get("labCost")),
      active: form.get("active") === "on",
    });
    setBusy(false);
    if (result.error) return setStatus(`Unable to save laboratory service: ${result.error.message}`);
    setEditing(null);
    event.currentTarget.reset();
    setStatus("Laboratory service saved. Its code was generated by the system.");
    await load(organization.id);
  }

  if (!email && accessError) return <AdminSignIn />;

  return <main><p className="eyebrow">Laboratory service catalog</p><h1>Laboratory services</h1>
    <section><h2>{editing ? "Edit laboratory service" : "Add laboratory service"}</h2><form className="stack narrow-form" onSubmit={handleSave}><Field label="Laboratory service"><Input name="name" defaultValue={editing?.name ?? ""} key={editing?.id ?? "new"} required /></Field><Field label="Lab cost (PHP)"><Input name="labCost" type="number" min="0" step="0.01" defaultValue={editing?.labCost ?? ""} key={`cost-${editing?.id ?? "new"}`} required /></Field><label><input name="active" type="checkbox" defaultChecked={editing?.active ?? true} key={`active-${editing?.id ?? "new"}`} /> Active</label><span className="table-actions"><Button type="submit" disabled={busy}>{editing ? "Save changes" : "Add service"}</Button>{editing && <Button type="button" variant="outline" onClick={() => setEditing(null)}>Cancel</Button>}</span></form></section>
    <DataTable caption="Laboratory services and their system-generated codes." data={services} emptyMessage="No laboratory services configured." getRowId={(service) => service.id} columns={[{ id: "code", header: "Code", cell: (service) => service.code }, { id: "name", header: "Laboratory service", cell: (service) => service.name }, { id: "cost", header: "Lab cost", cell: (service) => `PHP ${service.labCost.toFixed(2)}` }, { id: "status", header: "Status", cell: (service) => service.active ? "Active" : "Inactive" }, { id: "action", header: "", cell: (service) => <Button size="sm" variant="outline" onClick={() => setEditing(service)}>Edit</Button> }]} />
    <p className="hint" role="status">{status}</p></main>;
}
