export interface RequisitionDocumentData {
  requisition_number: string;
  requesting_department_name?: string;
  supply_department_name?: string;
  target_delivery_week: string;
  submitted_at: string;
  notes?: string | null;
  items: Array<{
    item_name?: string;
    unit_of_measure?: string;
    requested_quantity: number;
    dispersed_quantity: number;
    notes?: string | null;
  }>;
}

function csvValue(value: unknown) {
  const text = String(value ?? "");
  const safeText = /^[=+\-@]/.test(text) ? `'${text}` : text;
  return `"${safeText.replaceAll('"', '""')}"`;
}

function escapeHtml(value: unknown) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function displayDate(value: string) {
  const date = new Date(value);
  return Number.isNaN(date.valueOf())
    ? value
    : new Intl.DateTimeFormat("en-PH", { dateStyle: "medium" }).format(date);
}

export function buildRequisitionCsv(requisition: RequisitionDocumentData) {
  const lines = [
    ["Requisition #", "Requesting department", "Supply department", "Delivery week", "Submitted", "Notes"],
    [
      requisition.requisition_number,
      requisition.requesting_department_name ?? "Department",
      requisition.supply_department_name ?? "Supply Room",
      requisition.target_delivery_week,
      displayDate(requisition.submitted_at),
      requisition.notes ?? "",
    ],
    [],
    ["Item", "Unit", "Requested", "Dispersed", "Status", "Notes"],
    ...requisition.items.map((item) => [
      item.item_name ?? "Item",
      item.unit_of_measure ?? "",
      item.requested_quantity,
      item.dispersed_quantity,
      "Dispersed",
      item.notes ?? "",
    ]),
  ];

  return lines.map((line) => line.map(csvValue).join(",")).join("\n");
}

export function buildRequisitionPrintDocument(requisition: RequisitionDocumentData) {
  const rows = requisition.items
    .map(
      (item) => `<tr>
        <td><strong>${escapeHtml(item.item_name ?? "Item")}</strong>${
          item.notes ? `<small>${escapeHtml(item.notes)}</small>` : ""
        }</td>
        <td>${escapeHtml(item.unit_of_measure ?? "")}</td>
        <td class="number">${escapeHtml(item.requested_quantity)}</td>
        <td class="number">${escapeHtml(item.dispersed_quantity)}</td>
      </tr>`
    )
    .join("");

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Dispersion Receipt ${escapeHtml(requisition.requisition_number)}</title>
    <style>
      @page { size: A5 portrait; margin: 7mm; }
      * { box-sizing: border-box; }
      body { color: #0f172a; font: 9pt/1.3 Arial, sans-serif; margin: 0; }
      .header { border-bottom: 1.5px solid #0f172a; padding-bottom: 4mm; }
      h1 { font-size: 13pt; margin: 0; }
      .muted { color: #475569; }
      .details { display: grid; gap: 1mm 5mm; grid-template-columns: 1fr 1fr; margin: 4mm 0; }
      .details div { min-width: 0; }
      .label { color: #64748b; display: block; font-size: 7.5pt; text-transform: uppercase; }
      table { border-collapse: collapse; width: 100%; }
      th { background: #f1f5f9; font-size: 7.5pt; letter-spacing: .03em; text-align: left; text-transform: uppercase; }
      th, td { border-bottom: 1px solid #cbd5e1; padding: 2.2mm 1.5mm; vertical-align: top; }
      .number { text-align: right; white-space: nowrap; }
      small { color: #475569; display: block; font-size: 7.5pt; font-style: italic; margin-top: 1mm; }
      .footer { border-top: 1px solid #cbd5e1; color: #64748b; font-size: 7.5pt; margin-top: 4mm; padding-top: 2mm; }
    </style>
  </head>
  <body>
    <header class="header">
      <h1>Inventory Dispersion Receipt</h1>
      <span class="muted">${escapeHtml(requisition.requisition_number)} &middot; Fully dispersed</span>
    </header>
    <section class="details">
      <div><span class="label">Requesting department</span>${escapeHtml(requisition.requesting_department_name ?? "Department")}</div>
      <div><span class="label">Supply department</span>${escapeHtml(requisition.supply_department_name ?? "Supply Room")}</div>
      <div><span class="label">Delivery week</span>${escapeHtml(requisition.target_delivery_week)}</div>
      <div><span class="label">Submitted</span>${escapeHtml(displayDate(requisition.submitted_at))}</div>
    </section>
    ${requisition.notes ? `<p class="muted"><strong>Notes:</strong> ${escapeHtml(requisition.notes)}</p>` : ""}
    <table>
      <thead><tr><th>Item</th><th>Unit</th><th class="number">Requested</th><th class="number">Dispersed</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <footer class="footer">Generated by Odyssey Healthcare OS &middot; This receipt reflects dispensed inventory only.</footer>
  </body>
</html>`;
}
